In [1]:
import numpy as np

In [7]:
np.random.rand()

0.9299319240045864

In [12]:
np.random.randint(10, 20, [5, 5])

array([[17, 12, 17, 11, 12],
       [11, 18, 13, 14, 16],
       [16, 19, 18, 11, 17],
       [11, 19, 15, 19, 10],
       [19, 11, 14, 17, 13]])

In [13]:
first = np.random.randint(10, 20, [5, 4])

In [14]:
second = np.random.randint(10, 20, [5, 4])

In [16]:
first

array([[14, 12, 10, 17],
       [10, 11, 13, 15],
       [17, 11, 12, 19],
       [13, 10, 10, 12],
       [17, 15, 14, 14]])

In [19]:
second

array([[16, 19, 15, 18],
       [14, 12, 15, 14],
       [17, 15, 16, 19],
       [12, 10, 11, 19],
       [14, 16, 13, 12]])

In [15]:
third = np.hstack([first, second])

In [17]:
third.shape

(5, 8)

In [18]:
third

array([[14, 12, 10, 17, 16, 19, 15, 18],
       [10, 11, 13, 15, 14, 12, 15, 14],
       [17, 11, 12, 19, 17, 15, 16, 19],
       [13, 10, 10, 12, 12, 10, 11, 19],
       [17, 15, 14, 14, 14, 16, 13, 12]])

In [20]:
np.vstack([first, second])

array([[14, 12, 10, 17],
       [10, 11, 13, 15],
       [17, 11, 12, 19],
       [13, 10, 10, 12],
       [17, 15, 14, 14],
       [16, 19, 15, 18],
       [14, 12, 15, 14],
       [17, 15, 16, 19],
       [12, 10, 11, 19],
       [14, 16, 13, 12]])

In [24]:
np.concatenate([first, second], axis=1)

array([[14, 12, 10, 17, 16, 19, 15, 18],
       [10, 11, 13, 15, 14, 12, 15, 14],
       [17, 11, 12, 19, 17, 15, 16, 19],
       [13, 10, 10, 12, 12, 10, 11, 19],
       [17, 15, 14, 14, 14, 16, 13, 12]])

In [25]:
np.sum(first)

266

In [26]:
np.sum(first, axis=0)

array([71, 59, 59, 77])

In [27]:
first

array([[14, 12, 10, 17],
       [10, 11, 13, 15],
       [17, 11, 12, 19],
       [13, 10, 10, 12],
       [17, 15, 14, 14]])

In [28]:
np.sum(first, axis=1)

array([53, 49, 59, 45, 60])

In [29]:
first

array([[14, 12, 10, 17],
       [10, 11, 13, 15],
       [17, 11, 12, 19],
       [13, 10, 10, 12],
       [17, 15, 14, 14]])

In [31]:
first.size

20

In [33]:
another = first.reshape((2, 10))

In [34]:
first[0, 0] = 0

In [35]:
another

array([[ 0, 12, 10, 17, 10, 11, 13, 15, 17, 11],
       [12, 19, 13, 10, 10, 12, 17, 15, 14, 14]])

In [36]:
fourth = another.copy()

In [37]:
fourth[0]= 100

In [38]:
another

array([[ 0, 12, 10, 17, 10, 11, 13, 15, 17, 11],
       [12, 19, 13, 10, 10, 12, 17, 15, 14, 14]])

In [39]:
fourth

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 12,  19,  13,  10,  10,  12,  17,  15,  14,  14]])