In [6]:
import pandas as pd
import numpy as np

In [7]:
scores = np.random.randint(20, 30, (10,))

In [8]:
scores

array([27, 27, 25, 24, 29, 24, 23, 25, 22, 21])

In [10]:
scores = pd.Series(scores, name="Scores")

In [11]:
rolenos  = pd.Series(range(100, 110), name="Roll No.")

In [12]:
scores

0    27
1    27
2    25
3    24
4    29
5    24
6    23
7    25
8    22
9    21
Name: Scores, dtype: int64

In [13]:
rolenos

0    100
1    101
2    102
3    103
4    104
5    105
6    106
7    107
8    108
9    109
Name: Roll No., dtype: int64

In [16]:
df = pd.DataFrame({
    "Roll Nos" : rolenos,
    "Scores" : scores
})

In [17]:
df 

Roll Nos  Scores
0       100      27
1       101      27
2       102      25
3       103      24
4       104      29
5       105      24
6       106      23
7       107      25
8       108      22
9       109      21

In [18]:
pd.date_range("20130101", periods=6)

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [24]:
gen = np.random.randn(1000, 400)

In [25]:
gen.mean()

7.019574182344122e-05

In [26]:
gen.std()

0.9992120137205965

In [27]:
list("ABCD")

['A', 'B', 'C', 'D']

In [29]:
df["loc"] = "Delhi"

In [30]:
df

Roll Nos  Scores    loc
0       100      27  Delhi
1       101      27  Delhi
2       102      25  Delhi
3       103      24  Delhi
4       104      29  Delhi
5       105      24  Delhi
6       106      23  Delhi
7       107      25  Delhi
8       108      22  Delhi
9       109      21  Delhi

In [32]:
df["another"] = "Delhi"

In [33]:
df

Roll Nos  Scores    loc another
0       100      27  Delhi   Delhi
1       101      27  Delhi   Delhi
2       102      25  Delhi   Delhi
3       103      24  Delhi   Delhi
4       104      29  Delhi   Delhi
5       105      24  Delhi   Delhi
6       106      23  Delhi   Delhi
7       107      25  Delhi   Delhi
8       108      22  Delhi   Delhi
9       109      21  Delhi   Delhi

In [34]:
item = np.zeros([3, 3, 2])

In [35]:
item

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [39]:
# item1 = np.ones([1, 3, 2])

In [40]:
# item + item1

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [43]:
type(df.dtypes)

pandas.core.series.Series

In [44]:
df.dtypes

Roll Nos     int64
Scores       int64
loc         object
another     object
dtype: object

In [48]:
out = df.head(2)

In [49]:
type(out)

pandas.core.frame.DataFrame

In [50]:
out

Roll Nos  Scores    loc another
0       100      27  Delhi   Delhi
1       101      27  Delhi   Delhi

In [51]:
df.describe()

Roll Nos     Scores
count   10.00000  10.000000
mean   104.50000  24.700000
std      3.02765   2.451757
min    100.00000  21.000000
25%    102.25000  23.250000
50%    104.50000  24.500000
75%    106.75000  26.500000
max    109.00000  29.000000

In [52]:
df.index

RangeIndex(start=0, stop=10, step=1)

In [53]:
df.columns

Index(['Roll Nos', 'Scores', 'loc', 'another'], dtype='object')

In [55]:
df.sort_index(axis=0, ascending=False)

Roll Nos  Scores    loc another
9       109      21  Delhi   Delhi
8       108      22  Delhi   Delhi
7       107      25  Delhi   Delhi
6       106      23  Delhi   Delhi
5       105      24  Delhi   Delhi
4       104      29  Delhi   Delhi
3       103      24  Delhi   Delhi
2       102      25  Delhi   Delhi
1       101      27  Delhi   Delhi
0       100      27  Delhi   Delhi

In [58]:
df.sort_values(by="Scores", axis=0)

Roll Nos  Scores    loc another
9       109      21  Delhi   Delhi
8       108      22  Delhi   Delhi
6       106      23  Delhi   Delhi
3       103      24  Delhi   Delhi
5       105      24  Delhi   Delhi
2       102      25  Delhi   Delhi
7       107      25  Delhi   Delhi
0       100      27  Delhi   Delhi
1       101      27  Delhi   Delhi
4       104      29  Delhi   Delhi

In [65]:
values = np.random.randint(10, 20, (10, 4))

In [66]:
data = pd.DataFrame(values)

In [67]:
data

0   1   2   3
0  18  17  10  19
1  10  14  15  10
2  12  16  15  16
3  17  11  16  10
4  10  16  16  15
5  12  12  11  17
6  12  15  11  13
7  18  14  13  14
8  17  14  14  19
9  19  14  10  10

In [68]:
data.sort_values(by=1, axis=1)

0   3   1   2
0  18  19  17  10
1  10  10  14  15
2  12  16  16  15
3  17  10  11  16
4  10  15  16  16
5  12  17  12  11
6  12  13  15  11
7  18  14  14  13
8  17  19  14  14
9  19  10  14  10

In [69]:
df

Roll Nos  Scores    loc another
0       100      27  Delhi   Delhi
1       101      27  Delhi   Delhi
2       102      25  Delhi   Delhi
3       103      24  Delhi   Delhi
4       104      29  Delhi   Delhi
5       105      24  Delhi   Delhi
6       106      23  Delhi   Delhi
7       107      25  Delhi   Delhi
8       108      22  Delhi   Delhi
9       109      21  Delhi   Delhi

In [70]:
df.columns

Index(['Roll Nos', 'Scores', 'loc', 'another'], dtype='object')

In [71]:
df['Roll Nos']

0    100
1    101
2    102
3    103
4    104
5    105
6    106
7    107
8    108
9    109
Name: Roll Nos, dtype: int64

In [72]:
df[['Roll Nos', 'loc']]

Roll Nos    loc
0       100  Delhi
1       101  Delhi
2       102  Delhi
3       103  Delhi
4       104  Delhi
5       105  Delhi
6       106  Delhi
7       107  Delhi
8       108  Delhi
9       109  Delhi

In [73]:
s = set("hello")

In [74]:
s

{'e', 'h', 'l', 'o'}

In [75]:
s[0]

TypeError: 'set' object is not subscriptable

In [76]:
df[0:1]

Roll Nos  Scores    loc another
0       100      27  Delhi   Delhi

In [82]:
df.iloc[2:10:2, [0, 2]]

Roll Nos    loc
2       102  Delhi
4       104  Delhi
6       106  Delhi
8       108  Delhi

In [83]:
li = list(range(10))

In [84]:
li

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [85]:
li[::-1]

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [88]:
df.iloc[:, ::-1]

another    loc  Scores  Roll Nos
0   Delhi  Delhi      27       100
1   Delhi  Delhi      27       101
2   Delhi  Delhi      25       102
3   Delhi  Delhi      24       103
4   Delhi  Delhi      29       104
5   Delhi  Delhi      24       105
6   Delhi  Delhi      23       106
7   Delhi  Delhi      25       107
8   Delhi  Delhi      22       108
9   Delhi  Delhi      21       109

In [89]:
another = df.iloc[3:7]

In [90]:
another

Roll Nos  Scores    loc another
3       103      24  Delhi   Delhi
4       104      29  Delhi   Delhi
5       105      24  Delhi   Delhi
6       106      23  Delhi   Delhi

In [95]:
another.loc[:4, ["Roll Nos", "loc"]]

Roll Nos    loc
3       103  Delhi
4       104  Delhi

In [96]:
another.loc[:4, [True, False, True, True]]

Roll Nos    loc another
3       103  Delhi   Delhi
4       104  Delhi   Delhi

In [97]:
df

Roll Nos  Scores    loc another
0       100      27  Delhi   Delhi
1       101      27  Delhi   Delhi
2       102      25  Delhi   Delhi
3       103      24  Delhi   Delhi
4       104      29  Delhi   Delhi
5       105      24  Delhi   Delhi
6       106      23  Delhi   Delhi
7       107      25  Delhi   Delhi
8       108      22  Delhi   Delhi
9       109      21  Delhi   Delhi

In [99]:
selected = df["Scores"] > 25

In [100]:
df.loc[selected]

Roll Nos  Scores    loc another
0       100      27  Delhi   Delhi
1       101      27  Delhi   Delhi
4       104      29  Delhi   Delhi

In [101]:
data

0   1   2   3
0  18  17  10  19
1  10  14  15  10
2  12  16  15  16
3  17  11  16  10
4  10  16  16  15
5  12  12  11  17
6  12  15  11  13
7  18  14  13  14
8  17  14  14  19
9  19  14  10  10

In [108]:
data.iloc[:4, :2]  = 100

In [109]:
data

0    1   2   3
0  100  100   0   0
1  100  100   0   0
2  100  100   0   0
3  100  100   0   0
4   10   16  16  15
5   12   12  11  17
6   12   15  11  13
7   18   14  13  14
8   17   14  14  19
9   19   14  10  10

In [ ]:
pd.s