In [1]:
from sklearn.datasets import make_regression
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

bias = 100
X, y, coef = make_regression(n_samples=500,  n_features=4, bias=bias, coef=True, noise=3, random_state=42)

In [3]:
np.hstack([np.ones([X.shape[0], 1]),  X])

array([[ 1.        , -0.92323325, -1.4066611 , -0.6115178 , -1.35168461],
       [ 1.        , -1.34445051, -0.28178461, -0.42018682, -0.91865195],
       [ 1.        , -2.0674421 , -0.03269475,  0.38406545, -0.08912004],
       ...,
       [ 1.        , -0.74247059,  0.19460746, -0.62264936, -1.32002251],
       [ 1.        ,  0.39445214, -0.43255819, -0.48760622, -0.42098448],
       [ 1.        ,  0.38019785, -1.33534436,  0.177701  ,  0.61058575]])

In [15]:
class CustomLinearReg:
        
    def fit(self, X, y):
        self.__X = np.hstack([np.ones([X.shape[0], 1]),  X])
        self.__ya = y.reshape(-1, 1)
        
        first = np.linalg.inv(np.dot(self.__X.T, self.__X))
        second = np.dot(self.__X.T, self.__ya)
        
        self.theta_ = np.dot(first, second)
        
    
    def predict(self, X):
        X = np.hstack([np.ones([X.shape[0], 1]),  X])
        yp = np.dot(X, self.theta_)
        return yp.flatten()

In [16]:
model = CustomLinearReg()

In [17]:
X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.33, random_state=42)

In [18]:
model.fit(X_train, y_train)

In [19]:
X_test[:10]

array([[ 0.05963037,  0.92463368,  1.39935544, -0.64693678],
       [ 0.91831661,  1.39200229,  0.17989415, -1.5705006 ],
       [-1.02418682,  0.63081168,  1.51344974,  1.85409257],
       [-0.53025762,  0.50404652, -0.98572605, -0.79287283],
       [ 0.44381943, -0.70766947,  1.26691115,  0.77463405],
       [ 0.02079371,  2.05749547,  0.61915426, -0.72800294],
       [ 1.58601682,  0.66213067,  0.11351735, -1.2378155 ],
       [ 0.79426468, -0.52905268, -1.56254586, -1.25428942],
       [-0.24896415,  1.75534084,  2.06074792,  0.97157095],
       [ 1.42050425,  1.18901653, -0.63738713, -0.57074629]])

In [20]:
model.predict(X_test[:10])

array([158.36878191, 131.4646273 , 151.17584654,  36.39367868,
       170.75690415, 132.1994275 , 150.51933671,  46.52311344,
       198.25701846, 125.26271395])

In [21]:
y_test[:10]

array([154.21413459, 126.60346289, 150.48587768,  32.91739582,
       175.253328  , 130.61733492, 148.72312993,  43.91310513,
       199.39079722, 124.91676786])