In [31]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import numpy as np

In [2]:
df = pd.read_csv("../datasets/NationalNames.csv")

In [4]:
selected = df[["Name", "Gender"]]

In [7]:
selected["Gender"] = LabelEncoder().fit_transform(selected.Gender)

<ipython-input-7-cd49e77e5904>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected["Gender"] = LabelEncoder().fit_transform(selected.Gender)


In [13]:
X = selected.Name.apply(str.lower)

In [16]:
X_mod = [list(name) for name in X]

In [18]:
# X_mod

In [19]:
import string

In [22]:
letters = list(string.ascii_lowercase)

In [24]:
vocab = dict(zip(letters, range(len(letters))))

In [25]:
vocab

{'a': 0,
 'b': 1,
 'c': 2,
 'd': 3,
 'e': 4,
 'f': 5,
 'g': 6,
 'h': 7,
 'i': 8,
 'j': 9,
 'k': 10,
 'l': 11,
 'm': 12,
 'n': 13,
 'o': 14,
 'p': 15,
 'q': 16,
 'r': 17,
 's': 18,
 't': 19,
 'u': 20,
 'v': 21,
 'w': 22,
 'x': 23,
 'y': 24,
 'z': 25}

In [26]:
name = [0]* 26

real = "kunal"

for ch in real:
    name[vocab[ch]] += 1

In [30]:
X_cut = X_mod[:2000]

In [36]:
X_gen = np.zeros([2000, 26], dtype=int)

In [37]:
for idx, real in enumerate(X_cut):
    name = X_gen[idx]
    for ch in real:
        name[vocab[ch]] += 1


In [38]:
X_gen[:2]

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 1, 0],
       [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0]])

In [41]:
y_gen = selected["Gender"].values[:2000]

In [42]:
y_gen

array([0, 0, 0, ..., 1, 1, 1])

In [49]:
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import train_test_split

In [51]:
X_train, X_test, y_train, y_test = train_test_split(
...     X_gen, y_gen, test_size=0.33, random_state=42)

In [52]:
model = BernoulliNB()

In [53]:
model.fit(X_train, y_train)

BernoulliNB()

In [54]:
model.score(X_test, y_test)

0.6833333333333333

In [66]:
real = list("annie")

name = np.zeros((26,), dtype=int)
for ch in real:
    name[vocab[ch]] += 1

model.predict([name])

array([0])