In [1]:
from tensorflow.keras.datasets import imdb

In [2]:
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=1000)

17465344/17464789 [==============================] - 2s 0us/step


<__array_function__ internals>:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
/home/anuj/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/datasets/imdb.py:155: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  x_train, y_train = np.array(xs[:idx]), np.array(labels[:idx])
/home/anuj/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/datasets/imdb.py:156: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. 

In [3]:
vocab = imdb.get_word_index()

1646592/1641221 [==============================] - 0s 0us/step


In [5]:
min(X_train[1])

1

In [6]:
max(X_train[1])

954

In [7]:
# vocab

In [8]:
rev = [[value, key] for [key, value] in vocab.items()]

In [9]:
rev_vocab = dict(rev)

In [10]:
min(list(rev_vocab.keys()))

1

In [11]:
rev_vocab[1]

'the'

In [12]:
sent = X_train[6]

In [13]:
" ".join([rev_vocab[idx-3] for idx in sent if idx > 3])

"production and performances in this of classic about the game within and between the in and are a as friends who must through and to that they love each other good humor is a which goes a long way towards the of the material which has been down a bit in its i liked the look of the film and how shots were set up and i thought it didn't too much on of head shots like most other films of the and do very good"

In [15]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [16]:
X_train_mod = pad_sequences(X_train, maxlen=100)
X_test_mod = pad_sequences(X_test, maxlen=100)

In [17]:
X_train_mod.shape

(25000, 100)

In [19]:
from tensorflow.keras.layers import Input, Dense, LSTM, Embedding
from tensorflow.keras.models import Model

In [20]:
y_train[:10]

array([1, 0, 0, 1, 0, 0, 1, 0, 1, 0])

In [21]:
in_layer = Input(shape=(100,))
embedding = Embedding(input_dim=1001, output_dim=20)(in_layer)
rnn_layer = LSTM(units=100)(embedding)
out_layer = Dense(1, activation="sigmoid")(rnn_layer)

In [22]:
model = Model(in_layer, out_layer)

In [23]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 100)]             0         
_________________________________________________________________
embedding (Embedding)        (None, 100, 20)           20020     
_________________________________________________________________
lstm (LSTM)                  (None, 100)               48400     
_________________________________________________________________
dense (Dense)                (None, 1)                 101       
Total params: 68,521
Trainable params: 68,521
Non-trainable params: 0
_________________________________________________________________


In [24]:
model.compile(optimizer="adam", loss="mse", metrics=["accuracy"])

In [25]:
model.fit(X_train_mod, y_train, epochs=10, batch_size=1000)

Epoch 1/10
25/25 [==============================] - 52s 2s/step - loss: 0.2421 - accuracy: 0.5888
Epoch 2/10
25/25 [==============================] - 49s 2s/step - loss: 0.1977 - accuracy: 0.7102
Epoch 3/10
25/25 [==============================] - 56s 2s/step - loss: 0.1509 - accuracy: 0.7909
Epoch 4/10
25/25 [==============================] - 56s 2s/step - loss: 0.1311 - accuracy: 0.8181
Epoch 5/10
25/25 [==============================] - 52s 2s/step - loss: 0.1228 - accuracy: 0.8292
Epoch 6/10
25/25 [==============================] - 52s 2s/step - loss: 0.1170 - accuracy: 0.8389
Epoch 7/10
25/25 [==============================] - 53s 2s/step - loss: 0.1155 - accuracy: 0.8421
Epoch 8/10
25/25 [==============================] - 50s 2s/step - loss: 0.1143 - accuracy: 0.8441
Epoch 9/10
25/25 [==============================] - 52s 2s/step - loss: 0.1122 - accuracy: 0.8476
Epoch 10/10
25/25 [==============================] - 53s 2s/step - loss: 0.1104 - accuracy: 0.8526


In [27]:
model.evaluate(X_test_mod, y_test, verbose=0)

[0.12615881860256195, 0.8213599920272827]

In [ ]:
fromimdb

"please don't waste your time on this...its very boring. it's like they pre-sell the movie with a good ending of infinity war. its a rip off. trust me you won't believe this. i quite after 30 minutes.\n\ni am writing this review to alert people: keep your money and time for something else."

In [ ]:
from nltk.tokenize import word_tokenize
import nltk

In [ ]:
nltk.download("popular")

[nltk_data] Downloading collection 'popular'
[nltk_data]    | 
[nltk_data]    | Downloading package cmudict to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cmudict.zip.
[nltk_data]    | Downloading package gazetteers to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/gazetteers.zip.
[nltk_data]    | Downloading package genesis to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/genesis.zip.
[nltk_data]    | Downloading package gutenberg to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/gutenberg.zip.
[nltk_data]    | Downloading package inaugural to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/inaugural.zip.
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/movie_reviews.zip.
[nltk_data]    | Downloading package names to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/names.zip.
[nltk_data]    | Downloading package shakespeare to /root/nltk_data...
[nlt

True

In [ ]:
vocab_words = set([key for key in vocab.keys() if vocab[key] < 1000])

In [ ]:
fromimdb = r"""After Avengers Infinity War, we waited for the Avengers Endgame. We wondered how the story would go on, how our heroes would turn back, what would be the end of Thanos. Many theories related to this have been put forward. Avengers Endgame was undoubtedly the most anticipated film of recent years. Normally, the higher the expectation, the higher the probability of disappointment. But this is not the case for Endgame. Whatever you're expecting, you find much more in the film. This means that the biggest concern about the film has disappeared.

On the other hand, another comparison comes up. Is Endgame more successful than Infinity War? We can comfortably say it Avengers Infinity War is just the beginning of the story. Endgame was the finale of the story. So we shouldn't think of these two films as two separate stories. There is only one story divided into two parts.

Avengers Endgame is, above all, a great homage to the ten-year history of the Marvel Cinematic Universe. The story highlights the original Avengers team. Iron Man, Captain America, Thor, Hulk, Black Widow and Hawkeye are at the center of events. No character comes in front of them. Of course there are many characters that play an important role in the story outside the original Avengers team. Everyone's concern was that Captain Marvel, who was included in the Marvel world, overshadowed other heroes. We can say that this certainly did not happen. What is important in this struggle is not how strong you are, but how good you are. This comes to the fore in all areas. It gives good message about being a hero and a family..""".lower()
words = word_tokenize(fromimdb)

In [ ]:
out = [vocab[word]+3 for word in words if word in vocab_words]

In [ ]:
X = pad_sequences([out], maxlen=100)

In [ ]:
X

array([[ 83, 107, 531,   9, 752,  32,   6,  87,   8,   4, 479,   7,   4,
          4,  65,   4, 204, 768, 132, 938, 328,   5,  26,  33,   4,   7,
        687,  57, 109, 266,  11,   7,  98,   7, 265,  50,  26, 111, 105,
         15, 297,  35, 674, 217,  11,   4,  65,   4, 204, 768, 316,  16,
         15,  37,  16,  11,   4, 182,  85,  75,  70, 135,  15,  14, 434,
        122,  24, 593,  51,   9, 674,  11,  14,   9,  24,  89, 565,  25,
         26,  21,  89,  52,  25,  26,  14, 266,   8,   4,  11,  32,  12,
        408,  52, 749,  44, 112,   6, 632,   5,   6]], dtype=int32)

In [ ]:
model.predict(X)

array([[0.9423405]], dtype=float32)